services:
  ngrok-dev:
    image: ngrok/ngrok:latest
    container_name: ngrok-dev
    command: start --all --config /etc/ngrok/ngrok.yml
    env_file:
      - .env
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml:ro
    restart: unless-stopped
    ports:
      - "4040:4040"
